import { Inter } from "next/font/google";
import { Abel } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const abel = Abel({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Coinbase Assignment | Ayush Tyagi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={abel.className}>{children}</body>
    </html>
  );
}
